// Documentation de l'API de script (autocomplétion + onglet Apprendre)
// Format des membres : "nom|genre|signature|description"  (genre : p = propriété, m = méthode, s = statique, e = événement, c = constante)

const raw = {
  MonoBehaviour: {
    desc: 'Classe de base de tous les scripts. Ajoute ton script à un GameObject via « Ajouter un composant ».',
    m: [
      'gameObject|p|gameObject|Le GameObject qui porte ce script',
      'transform|p|transform|Le Transform (position, rotation, échelle) du GameObject',
      'enabled|p|enabled|Active/désactive le script (Update n\'est plus appelé)',
      'name|p|name|Nom du GameObject',
      'tag|p|tag|Tag du GameObject',
      'GetComponent|m|GetComponent(type)|Renvoie un composant du GameObject : GetComponent("Rigidbody") ou GetComponent(Rigidbody)',
      'GetComponents|m|GetComponents(type)|Tous les composants de ce type',
      'GetComponentInChildren|m|GetComponentInChildren(type)|Cherche aussi dans les enfants',
      'GetComponentInParent|m|GetComponentInParent(type)|Cherche aussi dans les parents',
      'CompareTag|m|CompareTag(tag)|Vrai si le tag correspond',
      'StartCoroutine|m|StartCoroutine(this.MaRoutine())|Lance une coroutine (méthode déclarée avec *, utilisant yield)',
      'StopCoroutine|m|StopCoroutine(routine)|Arrête une coroutine',
      'StopAllCoroutines|m|StopAllCoroutines()|Arrête toutes les coroutines du script',
      'Invoke|m|Invoke("Methode", delai)|Appelle une méthode après un délai (secondes)',
      'InvokeRepeating|m|InvokeRepeating("Methode", delai, intervalle)|Appelle une méthode en boucle',
      'CancelInvoke|m|CancelInvoke("Methode")|Annule les Invoke',
      'SendMessage|m|SendMessage("Methode", ...args)|Appelle une méthode sur tous les scripts du GameObject',
      'print|m|print(...valeurs)|Affiche dans la console',
    ],
  },
  'Événements': {
    desc: 'Méthodes appelées automatiquement par le moteur si elles existent dans ton script.',
    m: [
      'Awake|e|Awake()|À la création de l\'objet (avant Start)',
      'OnEnable|e|OnEnable()|Quand le script/l\'objet devient actif',
      'Start|e|Start()|Avant la première image (peut être une coroutine : *Start())',
      'Update|e|Update()|À chaque image — utilise Time.deltaTime',
      'FixedUpdate|e|FixedUpdate()|À pas fixe (60 Hz), idéal pour la physique',
      'LateUpdate|e|LateUpdate()|Après tous les Update (caméras qui suivent)',
      'OnDisable|e|OnDisable()|Quand le script/l\'objet est désactivé',
      'OnDestroy|e|OnDestroy()|Quand l\'objet est détruit',
      'OnCollisionEnter|e|OnCollisionEnter(collision)|Début d\'un contact physique. collision.gameObject = l\'autre objet',
      'OnCollisionStay|e|OnCollisionStay(collision)|Pendant le contact',
      'OnCollisionExit|e|OnCollisionExit(collision)|Fin du contact',
      'OnTriggerEnter|e|OnTriggerEnter(other)|Entrée dans un déclencheur (collider « Déclencheur »). other.gameObject, other.CompareTag()',
      'OnTriggerStay|e|OnTriggerStay(other)|Pendant la présence dans le déclencheur',
      'OnTriggerExit|e|OnTriggerExit(other)|Sortie du déclencheur',
      'OnMouseDown|e|OnMouseDown()|L\'objet est touché (doigt ou souris)',
      'OnMouseUp|e|OnMouseUp()|Le doigt est relâché',
      'OnMouseDrag|e|OnMouseDrag()|Le doigt glisse après avoir touché l\'objet',
      'OnMouseUpAsButton|e|OnMouseUpAsButton()|Relâché sur le même objet (comme un bouton)',
      'OnClick|e|OnClick(button)|Appelé par un UI Button (nom de méthode configurable)',
    ],
  },
  Transform: {
    desc: 'Position, rotation et échelle. Accès : this.transform. « Avant » = -Z.',
    m: [
      'position|p|position|Position monde (Vector3). Modifiable : this.transform.position.x += 1',
      'localPosition|p|localPosition|Position relative au parent',
      'rotation|p|rotation|Rotation monde (Quaternion)',
      'localRotation|p|localRotation|Rotation relative au parent',
      'eulerAngles|p|eulerAngles|Rotation monde en degrés (Vector3)',
      'localEulerAngles|p|localEulerAngles|Rotation locale en degrés',
      'localScale|p|localScale|Échelle (Vector3)',
      'lossyScale|p|lossyScale|Échelle monde (lecture)',
      'forward|p|forward|Direction avant (-Z local) en monde',
      'right|p|right|Direction droite en monde',
      'up|p|up|Direction haut en monde',
      'parent|p|parent|Transform parent (ou null)',
      'root|p|root|Transform racine',
      'childCount|p|childCount|Nombre d\'enfants',
      'children|p|children|Tableau des enfants',
      'GetChild|m|GetChild(i)|Enfant n° i',
      'Find|m|Find("Nom/SousNom")|Cherche un enfant par nom',
      'SetParent|m|SetParent(parent, garderPositionMonde = true)|Change de parent',
      'Translate|m|Translate(x, y, z, Space.Self)|Déplace (repère local par défaut)',
      'Rotate|m|Rotate(x, y, z, Space.Self)|Tourne en degrés',
      'RotateAround|m|RotateAround(point, axe, angle)|Tourne autour d\'un point',
      'LookAt|m|LookAt(cible)|Oriente l\'avant (-Z) vers une cible (Transform, GameObject ou Vector3)',
      'TransformPoint|m|TransformPoint(v)|Local → monde',
      'InverseTransformPoint|m|InverseTransformPoint(v)|Monde → local',
      'TransformDirection|m|TransformDirection(v)|Direction locale → monde',
      'InverseTransformDirection|m|InverseTransformDirection(v)|Direction monde → locale',
      'DetachChildren|m|DetachChildren()|Détache tous les enfants',
    ],
  },
  GameObject: {
    desc: 'Un objet de la scène. Contient des composants.',
    m: [
      'name|p|name|Nom',
      'tag|p|tag|Tag (ex. "Player")',
      'transform|p|transform|Son Transform',
      'activeSelf|p|activeSelf|Actif lui-même',
      'activeInHierarchy|p|activeInHierarchy|Actif en tenant compte des parents',
      'SetActive|m|SetActive(bool)|Active/désactive',
      'GetComponent|m|GetComponent(type)|Renvoie un composant',
      'AddComponent|m|AddComponent("Rigidbody")|Ajoute un composant (ou un script par nom)',
      'CompareTag|m|CompareTag(tag)|Vrai si le tag correspond',
      'SendMessage|m|SendMessage("Methode", ...args)|Appelle une méthode sur ses scripts',
      'BroadcastMessage|m|BroadcastMessage("Methode", ...args)|Idem, enfants compris',
      'Find|s|GameObject.Find("Nom")|Trouve un objet actif par son nom',
      'FindWithTag|s|GameObject.FindWithTag("Player")|Trouve un objet par tag',
      'FindGameObjectsWithTag|s|GameObject.FindGameObjectsWithTag("Enemy")|Tous les objets avec ce tag',
      'FindObjectOfType|s|GameObject.FindObjectOfType("GameManager")|Premier composant de ce type',
      'CreatePrimitive|s|GameObject.CreatePrimitive("Cube")|Crée un cube, sphère… avec collider',
    ],
  },
  Global: {
    desc: 'Fonctions globales disponibles dans tous les scripts.',
    m: [
      'Instantiate|m|Instantiate(original, position?, rotation?, parent?)|Clone un GameObject ou un prefab. Renvoie le nouvel objet',
      'Destroy|m|Destroy(objet, delai = 0)|Détruit un GameObject ou un composant',
      'DontDestroyOnLoad|m|DontDestroyOnLoad(gameObject)|Garde l\'objet lors d\'un changement de scène',
      'print|m|print(...valeurs)|Affiche dans la console',
    ],
  },
  Vector3: {
    desc: 'Vecteur 3D. Les opérations renvoient un nouveau vecteur : a.add(b), a.mul(2)…',
    m: [
      'zero|s|Vector3.zero|(0, 0, 0)', 'one|s|Vector3.one|(1, 1, 1)', 'up|s|Vector3.up|(0, 1, 0)', 'down|s|Vector3.down|(0, -1, 0)',
      'left|s|Vector3.left|(-1, 0, 0)', 'right|s|Vector3.right|(1, 0, 0)', 'forward|s|Vector3.forward|(0, 0, -1)', 'back|s|Vector3.back|(0, 0, 1)',
      'Distance|s|Vector3.Distance(a, b)|Distance entre deux points',
      'Lerp|s|Vector3.Lerp(a, b, t)|Interpolation linéaire',
      'MoveTowards|s|Vector3.MoveTowards(actuel, cible, pasMax)|Avance vers une cible',
      'Dot|s|Vector3.Dot(a, b)|Produit scalaire', 'Cross|s|Vector3.Cross(a, b)|Produit vectoriel',
      'Angle|s|Vector3.Angle(a, b)|Angle en degrés', 'Reflect|s|Vector3.Reflect(dir, normale)|Réflexion',
      'ClampMagnitude|s|Vector3.ClampMagnitude(v, max)|Limite la longueur',
      'ProjectOnPlane|s|Vector3.ProjectOnPlane(v, normale)|Projection sur un plan',
      'x|p|x|Composante X', 'y|p|y|Composante Y', 'z|p|z|Composante Z',
      'magnitude|p|magnitude|Longueur', 'sqrMagnitude|p|sqrMagnitude|Longueur au carré', 'normalized|p|normalized|Vecteur unitaire',
      'add|m|add(v)|Addition', 'sub|m|sub(v)|Soustraction', 'mul|m|mul(s)|Multiplication (nombre ou vecteur)', 'div|m|div(s)|Division',
      'neg|m|neg()|Opposé', 'dot|m|dot(v)|Produit scalaire', 'cross|m|cross(v)|Produit vectoriel', 'distanceTo|m|distanceTo(v)|Distance',
      'withX|m|withX(x)|Copie avec un autre X', 'withY|m|withY(y)|Copie avec un autre Y', 'withZ|m|withZ(z)|Copie avec un autre Z', 'clone|m|clone()|Copie',
    ],
  },
  Vector2: {
    desc: 'Vecteur 2D (positions écran, joystick…)',
    m: ['zero|s|Vector2.zero|(0, 0)', 'one|s|Vector2.one|(1, 1)', 'up|s|Vector2.up|(0, 1)', 'right|s|Vector2.right|(1, 0)', 'Distance|s|Vector2.Distance(a, b)|Distance', 'Lerp|s|Vector2.Lerp(a, b, t)|Interpolation',
      'x|p|x|X', 'y|p|y|Y', 'magnitude|p|magnitude|Longueur', 'normalized|p|normalized|Unitaire', 'add|m|add(v)|Addition', 'sub|m|sub(v)|Soustraction', 'mul|m|mul(s)|Multiplication', 'toVector3|m|toVector3(z)|Conversion'],
  },
  Quaternion: {
    desc: 'Rotation. q.mul(v) tourne un vecteur, q.mul(q2) compose.',
    m: ['identity|s|Quaternion.identity|Aucune rotation', 'Euler|s|Quaternion.Euler(x, y, z)|Depuis des angles en degrés', 'AngleAxis|s|Quaternion.AngleAxis(angle, axe)|Rotation autour d\'un axe',
      'LookRotation|s|Quaternion.LookRotation(direction, haut)|Regarde dans une direction', 'Slerp|s|Quaternion.Slerp(a, b, t)|Interpolation', 'RotateTowards|s|Quaternion.RotateTowards(a, b, degresMax)|Tourne progressivement',
      'Inverse|s|Quaternion.Inverse(q)|Inverse', 'Angle|s|Quaternion.Angle(a, b)|Angle entre deux rotations', 'eulerAngles|p|eulerAngles|Angles en degrés', 'mul|m|mul(q ou v)|Composition / rotation d\'un vecteur'],
  },
  Color: {
    desc: 'Couleur RGBA (0 à 1). new Color(1, 0, 0) ou new Color("#ff0000")',
    m: ['red|s|Color.red|Rouge', 'green|s|Color.green|Vert', 'blue|s|Color.blue|Bleu', 'white|s|Color.white|Blanc', 'black|s|Color.black|Noir', 'yellow|s|Color.yellow|Jaune', 'cyan|s|Color.cyan|Cyan', 'magenta|s|Color.magenta|Magenta', 'orange|s|Color.orange|Orange', 'gray|s|Color.gray|Gris', 'clear|s|Color.clear|Transparent',
      'Lerp|s|Color.Lerp(a, b, t)|Mélange', 'HSVToRGB|s|Color.HSVToRGB(h, s, v)|Depuis teinte/saturation/valeur', 'hex|s|Color.hex("#ff8800")|Depuis un code hexadécimal',
      'r|p|r|Rouge', 'g|p|g|Vert', 'b|p|b|Bleu', 'a|p|a|Alpha', 'toHex|m|toHex()|Code hexadécimal', 'withAlpha|m|withAlpha(a)|Copie avec alpha'],
  },
  Mathf: {
    desc: 'Fonctions mathématiques.',
    m: ['PI|c|Mathf.PI|π', 'Deg2Rad|c|Mathf.Deg2Rad|Degrés → radians', 'Rad2Deg|c|Mathf.Rad2Deg|Radians → degrés', 'Infinity|c|Mathf.Infinity|∞',
      'Abs|s|Mathf.Abs(x)|Valeur absolue', 'Sin|s|Mathf.Sin(rad)|Sinus', 'Cos|s|Mathf.Cos(rad)|Cosinus', 'Atan2|s|Mathf.Atan2(y, x)|Angle', 'Sqrt|s|Mathf.Sqrt(x)|Racine', 'Pow|s|Mathf.Pow(x, p)|Puissance',
      'Min|s|Mathf.Min(a, b)|Minimum', 'Max|s|Mathf.Max(a, b)|Maximum', 'Clamp|s|Mathf.Clamp(v, min, max)|Borne une valeur', 'Clamp01|s|Mathf.Clamp01(v)|Borne entre 0 et 1',
      'Lerp|s|Mathf.Lerp(a, b, t)|Interpolation', 'InverseLerp|s|Mathf.InverseLerp(a, b, v)|Inverse de Lerp', 'MoveTowards|s|Mathf.MoveTowards(actuel, cible, pas)|Avance vers une valeur',
      'SmoothStep|s|Mathf.SmoothStep(a, b, t)|Interpolation douce', 'PingPong|s|Mathf.PingPong(t, longueur)|Va-et-vient', 'Repeat|s|Mathf.Repeat(t, longueur)|Boucle',
      'Round|s|Mathf.Round(x)|Arrondi', 'Floor|s|Mathf.Floor(x)|Partie entière', 'Ceil|s|Mathf.Ceil(x)|Arrondi supérieur', 'Sign|s|Mathf.Sign(x)|Signe (1 ou -1)',
      'PerlinNoise|s|Mathf.PerlinNoise(x, y)|Bruit de Perlin entre 0 et 1', 'LerpAngle|s|Mathf.LerpAngle(a, b, t)|Interpolation d\'angle', 'DeltaAngle|s|Mathf.DeltaAngle(a, b)|Différence d\'angle', 'SmoothDamp|s|Mathf.SmoothDamp(actuel, cible, refVitesse, temps)|Amortissement (refVitesse = {value:0})'],
  },
  Random: {
    desc: 'Nombres aléatoires.',
    m: ['Range|s|Random.Range(min, max)|Entiers : max exclu ; décimaux : max inclus', 'Float|s|Random.Float(min, max)|Toujours un décimal (ex. Random.Float(-1, 1))', 'Int|s|Random.Int(min, max)|Entier, max exclu', 'value|s|Random.value|Entre 0 et 1', 'insideUnitSphere|s|Random.insideUnitSphere|Point dans une sphère', 'insideUnitCircle|s|Random.insideUnitCircle|Point dans un cercle (Vector2)', 'onUnitSphere|s|Random.onUnitSphere|Direction aléatoire',
      'rotation|s|Random.rotation|Rotation aléatoire', 'ColorHSV|s|Random.ColorHSV()|Couleur vive aléatoire', 'Pick|s|Random.Pick(tableau)|Élément au hasard', 'Chance|s|Random.Chance(p)|Vrai avec une probabilité p', 'InitState|s|Random.InitState(graine)|Graine fixe'],
  },
  Time: {
    desc: 'Temps du jeu.',
    m: ['deltaTime|s|Time.deltaTime|Durée de la dernière image (s)', 'time|s|Time.time|Temps depuis le début (s)', 'fixedDeltaTime|s|Time.fixedDeltaTime|Pas de la physique', 'timeScale|s|Time.timeScale|Vitesse du temps (0 = pause, 0.5 = ralenti)', 'frameCount|s|Time.frameCount|Nombre d\'images', 'unscaledDeltaTime|s|Time.unscaledDeltaTime|deltaTime sans timeScale', 'timeSinceLevelLoad|s|Time.timeSinceLevelLoad|Temps depuis le chargement de la scène'],
  },
  Input: {
    desc: 'Clavier, écran tactile, joystick virtuel et boutons A/B.',
    m: ['GetAxis|s|Input.GetAxis("Horizontal")|-1 à 1 (joystick, flèches, WASD). "Vertical" aussi', 'GetAxisRaw|s|Input.GetAxisRaw("Horizontal")|-1, 0 ou 1 sans lissage',
      'GetButton|s|Input.GetButton("Jump")|Bouton maintenu ("Jump" = A/Espace, "Fire1" = B/X)', 'GetButtonDown|s|Input.GetButtonDown("Jump")|Bouton appuyé cette image', 'GetButtonUp|s|Input.GetButtonUp("Jump")|Bouton relâché cette image',
      'GetKey|s|Input.GetKey(KeyCode.Space)|Touche maintenue', 'GetKeyDown|s|Input.GetKeyDown(KeyCode.Space)|Touche appuyée cette image', 'GetKeyUp|s|Input.GetKeyUp(KeyCode.Space)|Touche relâchée',
      'GetMouseButton|s|Input.GetMouseButton(0)|Doigt/clic maintenu sur l\'écran de jeu', 'GetMouseButtonDown|s|Input.GetMouseButtonDown(0)|Toucher commencé', 'GetMouseButtonUp|s|Input.GetMouseButtonUp(0)|Toucher terminé',
      'mousePosition|s|Input.mousePosition|Position du doigt (pixels, origine en bas à gauche)', 'touchCount|s|Input.touchCount|Nombre de doigts', 'GetTouch|s|Input.GetTouch(i)|Doigt n° i : {position, deltaPosition, phase}', 'touches|s|Input.touches|Tous les doigts',
      'acceleration|s|Input.acceleration|Accéléromètre (en g)', 'joystick|s|Input.joystick|Joystick virtuel (Vector2)', 'anyKeyDown|s|Input.anyKeyDown|Une touche ou un toucher cette image', 'SetVirtualControls|s|Input.SetVirtualControls({joystick:false, buttonA:true})|Affiche/masque les contrôles tactiles'],
  },
  Debug: {
    desc: 'Console et dessins de débogage.',
    m: ['Log|s|Debug.Log(...valeurs)|Message', 'LogWarning|s|Debug.LogWarning(...valeurs)|Avertissement', 'LogError|s|Debug.LogError(...valeurs)|Erreur', 'DrawLine|s|Debug.DrawLine(a, b, Color.red, duree)|Trace une ligne', 'DrawRay|s|Debug.DrawRay(origine, direction, couleur)|Trace un rayon', 'Break|s|Debug.Break()|Met le jeu en pause'],
  },
  Physics: {
    desc: 'Requêtes physiques.',
    m: ['Raycast|s|Physics.Raycast(origine, direction, distanceMax)|Renvoie {point, normal, distance, gameObject, collider} ou null', 'RaycastAll|s|Physics.RaycastAll(origine, direction, distance)|Tous les impacts',
      'Linecast|s|Physics.Linecast(a, b)|Impact entre deux points', 'OverlapSphere|s|Physics.OverlapSphere(centre, rayon)|Colliders dans une sphère', 'CheckSphere|s|Physics.CheckSphere(centre, rayon)|Vrai si quelque chose touche', 'gravity|s|Physics.gravity|Gravité (Vector3)'],
  },
  Rigidbody: {
    desc: 'Corps physique. this.GetComponent("Rigidbody")',
    m: ['velocity|p|velocity|Vitesse (Vector3). rb.velocity.y = 5 fonctionne', 'angularVelocity|p|angularVelocity|Vitesse de rotation (rad/s)', 'mass|p|mass|Masse', 'useGravity|p|useGravity|Soumis à la gravité', 'isKinematic|p|isKinematic|Déplacé seulement par script', 'drag|p|drag|Frottement de l\'air', 'freezeRotation|p|freezeRotation|Bloque la rotation',
      'AddForce|m|AddForce(force, ForceMode.Impulse)|Pousse le corps (Force, Acceleration, Impulse, VelocityChange)', 'AddRelativeForce|m|AddRelativeForce(force, mode)|Force dans le repère local', 'AddTorque|m|AddTorque(couple, mode)|Fait tourner', 'AddExplosionForce|m|AddExplosionForce(force, centre, rayon)|Explosion',
      'MovePosition|m|MovePosition(position)|Déplace', 'MoveRotation|m|MoveRotation(rotation)|Tourne', 'Sleep|m|Sleep()|Endort', 'WakeUp|m|WakeUp()|Réveille'],
  },
  Collider: {
    desc: 'BoxCollider, SphereCollider, CapsuleCollider, CylinderCollider.',
    m: ['isTrigger|p|isTrigger|Déclencheur (traverse, appelle OnTrigger…)', 'attachedRigidbody|p|attachedRigidbody|Rigidbody associé', 'bounds|p|bounds|Boîte englobante {min, max, center, size}', 'size|p|size|Taille (BoxCollider)', 'radius|p|radius|Rayon (Sphere/Capsule)', 'center|p|center|Centre'],
  },
  MeshRenderer: {
    desc: 'Affiche un maillage 3D.',
    m: ['material|p|material|Matériau : material.color = Color.red, material.emissiveColor, material.opacity, material.metalness…', 'mesh|p|mesh|Forme : "Cube", "Sphere", "Cylinder"…', 'enabled|p|enabled|Visible ou non', 'bounds|p|bounds|Boîte englobante'],
  },
  SpriteRenderer: {
    desc: 'Affiche une image 2D ou une forme.',
    m: ['color|p|color|Teinte', 'flipX|p|flipX|Miroir horizontal', 'flipY|p|flipY|Miroir vertical', 'sprite|p|sprite|Nom de l\'image importée', 'shape|p|shape|Forme : "Square", "Circle", "Triangle"…', 'size|p|size|Taille (Vector2)', 'sortingOrder|p|sortingOrder|Ordre d\'affichage'],
  },
  Camera: {
    desc: 'Caméra. Camera.main = caméra principale.',
    m: ['main|s|Camera.main|Caméra principale', 'fieldOfView|p|fieldOfView|Champ de vision (degrés)', 'orthographic|p|orthographic|Projection orthographique (2D)', 'orthographicSize|p|orthographicSize|Demi-hauteur visible (ortho)', 'backgroundColor|p|backgroundColor|Couleur de fond',
      'ScreenPointToRay|m|ScreenPointToRay(Input.mousePosition)|Rayon depuis un point de l\'écran', 'ScreenToWorldPoint|m|ScreenToWorldPoint(new Vector3(x, y, distance))|Écran → monde', 'WorldToScreenPoint|m|WorldToScreenPoint(position)|Monde → écran'],
  },
  Light: { desc: 'Lumière.', m: ['intensity|p|intensity|Intensité', 'color|p|color|Couleur', 'range|p|range|Portée', 'spotAngle|p|spotAngle|Angle du projecteur', 'enabled|p|enabled|Allumée'] },
  AudioSource: {
    desc: 'Joue un son (effets intégrés : coin, jump, hit, explosion, laser, powerup, click, blip, lose, win, ou sons importés).',
    m: ['Play|m|Play()|Joue le son', 'Stop|m|Stop()|Arrête', 'PlayOneShot|m|PlayOneShot("sfx:coin", volume)|Joue un son en plus', 'isPlaying|p|isPlaying|En cours', 'clip|p|clip|Son ("sfx:coin" ou nom importé)', 'volume|p|volume|Volume (0-1)', 'pitch|p|pitch|Hauteur', 'loop|p|loop|Boucle'],
  },
  Audio: { desc: 'Raccourcis audio.', m: ['Play|s|Audio.Play("coin", volume, pitch)|Joue un effet ou un son importé', 'StopAll|s|Audio.StopAll()|Coupe tout', 'mute|s|Audio.mute|Muet'] },
  Animator: {
    desc: 'Joue les animations d\'un Modèle 3D (.glb) : this.GetComponentInChildren("Animator"). Héros fourni : Repos, Marche, Course, Saut, Chute, Danse, Salut.',
    m: ['Play|m|Play("Marche")|Joue une animation (en boucle)', 'CrossFade|m|CrossFade("Course", 0.2)|Passe en douceur à une animation (fondu en s)', 'Play|m|Play("Saut", 0.1, false)|Une seule fois (reste sur la dernière image)', 'Stop|m|Stop()|Arrête', 'IsPlaying|m|IsPlaying("Danse")|Cette animation est-elle jouée ?', 'current|p|current|Nom de l\'animation en cours', 'clips|p|clips|Liste des animations du modèle', 'speed|p|speed|Vitesse (1 = normale)', 'normalizedTime|p|normalizedTime|Avancement 0-1'],
  },
  ModelRenderer: { desc: 'Modèle 3D importé (.glb de Blender).', m: ['model|p|model|Nom du modèle', 'scale|p|scale|Taille', 'clips|p|clips|Animations du modèle', 'isLoaded|p|isLoaded|Modèle chargé'] },
  ParticleSystem: { desc: 'Particules.', m: ['Play|m|Play()|Démarre', 'Stop|m|Stop()|Arrête d\'émettre', 'Emit|m|Emit(n)|Émet n particules', 'Clear|m|Clear()|Efface', 'isPlaying|p|isPlaying|En cours', 'rate|p|rate|Particules par seconde', 'startColor|p|startColor|Couleur de départ', 'endColor|p|endColor|Couleur finale', 'speed|p|speed|Vitesse'] },
  Text: { desc: 'UI Text : this.GetComponent("Text")', m: ['text|p|text|Texte affiché', 'color|p|color|Couleur', 'fontSize|p|fontSize|Taille', 'enabled|p|enabled|Visible'] },
  Button: { desc: 'UI Button', m: ['onClick|p|onClick|onClick.AddListener(() => …)', 'text|p|text|Libellé', 'interactable|p|interactable|Cliquable'] },
  Image: { desc: 'UI Image (barres de vie…)', m: ['fillAmount|p|fillAmount|Remplissage 0-1', 'color|p|color|Couleur', 'sprite|p|sprite|Image', 'enabled|p|enabled|Visible'] },
  SceneManager: { desc: 'Scènes (ordre = liste du panneau Projet).', m: ['LoadScene|s|SceneManager.LoadScene("Niveau2")|Charge une scène par nom ou numéro', 'ReloadScene|s|SceneManager.ReloadScene()|Recharge la scène', 'GetActiveScene|s|SceneManager.GetActiveScene()|{name, buildIndex}', 'sceneCount|s|SceneManager.sceneCount|Nombre de scènes'] },
  PlayerPrefs: { desc: 'Sauvegarde persistante (records, réglages…).', m: ['SetInt|s|PlayerPrefs.SetInt("record", 10)|Enregistre un entier', 'GetInt|s|PlayerPrefs.GetInt("record", 0)|Lit un entier', 'SetFloat|s|PlayerPrefs.SetFloat(cle, v)|Décimal', 'GetFloat|s|PlayerPrefs.GetFloat(cle, def)|Décimal', 'SetString|s|PlayerPrefs.SetString(cle, v)|Texte', 'GetString|s|PlayerPrefs.GetString(cle, def)|Texte', 'HasKey|s|PlayerPrefs.HasKey(cle)|Existe ?', 'DeleteKey|s|PlayerPrefs.DeleteKey(cle)|Supprime', 'DeleteAll|s|PlayerPrefs.DeleteAll()|Tout effacer'] },
  Application: { desc: 'Application.', m: ['Quit|s|Application.Quit()|Quitte le jeu', 'isEditor|s|Application.isEditor|Dans l\'éditeur ?', 'isMobilePlatform|s|Application.isMobilePlatform|Sur mobile ?', 'OpenURL|s|Application.OpenURL(url)|Ouvre un lien'] },
  Screen: { desc: 'Écran de jeu.', m: ['width|s|Screen.width|Largeur (px)', 'height|s|Screen.height|Hauteur (px)', 'orientation|s|Screen.orientation|"Portrait" ou "Landscape"'] },
  KeyCode: { desc: 'Touches du clavier.', m: ['Space|c|KeyCode.Space|Espace', 'Return|c|KeyCode.Return|Entrée', 'Escape|c|KeyCode.Escape|Échap', 'LeftArrow|c|KeyCode.LeftArrow|←', 'RightArrow|c|KeyCode.RightArrow|→', 'UpArrow|c|KeyCode.UpArrow|↑', 'DownArrow|c|KeyCode.DownArrow|↓', 'W|c|KeyCode.W|W', 'A|c|KeyCode.A|A', 'S|c|KeyCode.S|S', 'D|c|KeyCode.D|D', 'LeftShift|c|KeyCode.LeftShift|Maj'] },
  ForceMode: { desc: 'Modes de AddForce.', m: ['Force|c|ForceMode.Force|Force continue (masse)', 'Acceleration|c|ForceMode.Acceleration|Accélération (sans masse)', 'Impulse|c|ForceMode.Impulse|Impulsion instantanée', 'VelocityChange|c|ForceMode.VelocityChange|Change la vitesse directement'] },
  Space: { desc: 'Repère pour Translate/Rotate.', m: ['Self|c|Space.Self|Repère local', 'World|c|Space.World|Repère monde'] },
  Ref: {
    desc: 'Champs réglables dans l\'inspecteur (comme les champs public de Unity).',
    m: ['GameObject|s|cible = Ref.GameObject("Joueur")|Référence à un objet de la scène (nom par défaut optionnel)', 'Prefab|s|balle = Ref.Prefab("Balle")|Référence à un prefab', 'Range|s|vitesse = Ref.Range(0, 10, 5)|Nombre avec curseur', 'Color|s|teinte = Ref.Color("#ff0000")|Couleur', 'Sound|s|son = Ref.Sound("coin")|Son'],
  },
  Prefabs: { desc: 'Accès direct aux prefabs du projet.', m: ['Prefabs|s|Prefabs.Balle|Le prefab nommé « Balle » (pour Instantiate)', 'Load|s|Resources.Load("Balle")|Idem par nom'] },
  Coroutines: {
    desc: 'Exécution étalée dans le temps : déclare une méthode avec * et utilise yield.',
    m: ['WaitForSeconds|s|yield new WaitForSeconds(1)|Attend 1 seconde', 'WaitUntil|s|yield new WaitUntil(() => condition)|Attend une condition', 'WaitWhile|s|yield new WaitWhile(() => condition)|Attend tant que', 'null|s|yield null|Attend l\'image suivante', 'number|s|yield 0.5|Raccourci : attend 0,5 s'],
  },
};

function parseMembers(list) {
  return list.map((s) => {
    const [name, kind, sig, doc] = s.split('|');
    return { name, kind, sig, doc };
  });
}

export const DOCS = Object.fromEntries(Object.entries(raw).map(([k, v]) => [k, { desc: v.desc, members: parseMembers(v.m) }]));

/** Types de retour connus pour enchaîner l'autocomplétion (a.b.c) */
export const MEMBER_TYPES = {
  transform: 'Transform', gameObject: 'GameObject', position: 'Vector3', localPosition: 'Vector3', localScale: 'Vector3', eulerAngles: 'Vector3', localEulerAngles: 'Vector3',
  forward: 'Vector3', right: 'Vector3', up: 'Vector3', velocity: 'Vector3', angularVelocity: 'Vector3', rotation: 'Quaternion', localRotation: 'Quaternion', parent: 'Transform', root: 'Transform',
  material: 'Material', main: 'Camera', gravity: 'Vector3', mousePosition: 'Vector3', acceleration: 'Vector3', normalized: 'Vector3', joystick: 'Vector2', color: 'Color',
};
export const MATERIAL_MEMBERS = parseMembers(['color|p|color|Couleur (Color)', 'emissiveColor|p|emissiveColor|Couleur d\'émission', 'emissiveIntensity|p|emissiveIntensity|Intensité émission', 'opacity|p|opacity|Opacité 0-1', 'metalness|p|metalness|Métal', 'roughness|p|roughness|Rugosité', 'mainTexture|p|mainTexture|Texture (nom d\'image)']);

export const SNIPPETS = [
  { label: 'class MonoBehaviour', detail: 'Nouveau script', code: 'class ${Nom} extends MonoBehaviour {\n\tStart() {\n\t\t${}\n\t}\n\n\tUpdate() {\n\t}\n}' },
  { label: 'Start', detail: 'Méthode Start()', code: 'Start() {\n\t${}\n}' },
  { label: 'Update', detail: 'Méthode Update()', code: 'Update() {\n\t${}\n}' },
  { label: 'FixedUpdate', detail: 'Méthode FixedUpdate()', code: 'FixedUpdate() {\n\t${}\n}' },
  { label: 'LateUpdate', detail: 'Méthode LateUpdate()', code: 'LateUpdate() {\n\t${}\n}' },
  { label: 'Awake', detail: 'Méthode Awake()', code: 'Awake() {\n\t${}\n}' },
  { label: 'OnCollisionEnter', detail: 'Collision', code: 'OnCollisionEnter(collision) {\n\t${}\n}' },
  { label: 'OnTriggerEnter', detail: 'Déclencheur', code: 'OnTriggerEnter(other) {\n\tif (other.CompareTag("${Player}")) {\n\t\t\n\t}\n}' },
  { label: 'OnTriggerExit', detail: 'Déclencheur', code: 'OnTriggerExit(other) {\n\t${}\n}' },
  { label: 'OnMouseDown', detail: 'Toucher', code: 'OnMouseDown() {\n\t${}\n}' },
  { label: 'coroutine', detail: 'Coroutine (*méthode)', code: '*${Routine}() {\n\tyield new WaitForSeconds(1);\n\t${}\n}' },
  { label: 'GetComponent', detail: 'Récupérer un composant', code: 'this.${rb} = this.GetComponent("${Rigidbody}");' },
  { label: 'Input.GetAxis', detail: 'Déplacement', code: 'const h = Input.GetAxis("Horizontal");\nconst v = Input.GetAxis("Vertical");' },
  { label: 'for', detail: 'Boucle for', code: 'for (let ${i} = 0; ${i} < ${n}; ${i}++) {\n\t${}\n}' },
  { label: 'for of', detail: 'Boucle for…of', code: 'for (const ${x} of ${liste}) {\n\t${}\n}' },
  { label: 'if', detail: 'Condition', code: 'if (${condition}) {\n\t${}\n}' },
  { label: 'Instantiate', detail: 'Créer un clone', code: 'const ${obj} = Instantiate(${this.prefab}, this.transform.position, Quaternion.identity);' },
];

export const TUTORIALS = [
  {
    title: 'Un héros modélisé dans Blender',
    icon: '🧑‍🎤',
    steps: [
      'Touche ＋ → « Personnages animés » → « Héros 3D (modèle Blender) ». Le modèle Blender, ses scripts et la caméra arrivent ensemble.',
      'Appuie sur ▶ : il marche, court, saute et tombe tout seul selon ses mouvements. Le bouton B le fait danser.',
      'Ses animations sont dans le composant Animator (objet « Modèle ») : choisis l\'animation de départ dans l\'Inspecteur.',
      'Dans un script : const anim = this.GetComponentInChildren("Animator"); anim.CrossFade("Salut", 0.2);',
      'Ton propre modèle : dans Blender, Fichier → Exporter → glTF 2.0, format « glTF binaire (.glb) », avec l\'armature et les animations (une action par animation).',
      'Puis Projet → 📥 Importer → ton fichier .glb, et touche-le pour le placer dans la scène.',
    ],
  },
  {
    title: 'Faire un perso qui bouge',
    icon: '🏃',
    steps: [
      'Dans l\'éditeur, touche ＋ puis « Personnages animés » → « Perso 3D animé » (ou « Héros 2D animé »).',
      'Il arrive avec ses scripts et ses animations, et la caméra le suit déjà.',
      'Appuie sur ▶ : joystick pour marcher, A pour sauter (deux fois pour un double saut). En 3D, glisse le doigt à droite de l\'écran pour tourner la caméra.',
      'Règle la vitesse, la hauteur du saut ou l\'amplitude des animations dans l\'Inspecteur, sans toucher au code.',
      'Pour donner un comportement à n\'importe quel objet : Inspecteur → Ajouter un composant → 📚 Bibliothèque de scripts (caméra, ennemi, pièce à ramasser, plateforme mobile…).',
      'Envie de voir comment ça marche ? Touche ✏️ à côté du script pour ouvrir son code et le modifier.',
    ],
  },
  {
    title: 'Premiers pas',
    icon: '🚀',
    steps: [
      'Dans le Hub, touche « Nouveau projet » et choisis un modèle (par ex. « Balle roulante 3D »).',
      'La vue Scène montre ton monde. Glisse un doigt pour tourner, deux doigts pour zoomer / déplacer.',
      'Touche un objet pour le sélectionner, puis utilise les outils Déplacer / Tourner / Échelle en haut à gauche de la vue.',
      "L'onglet Inspecteur affiche ses composants : modifie la couleur, ajoute un Rigidbody…",
      'Appuie sur ▶ en haut pour jouer. Le joystick et les boutons A/B apparaissent dans la vue Jeu.',
      'Appuie à nouveau sur ▶ pour arrêter : la scène revient à son état d\'avant (comme dans Unity).',
    ],
  },
  {
    title: 'Écrire un script',
    icon: '📜',
    steps: [
      'Projet → « + Script » → donne un nom, par ex. « Tourne ».',
      "L'éditeur de code s'ouvre. Dans Update(), écris : this.transform.Rotate(0, 90 * Time.deltaTime, 0);",
      "Reviens à l'éditeur, sélectionne un cube et fais Ajouter un composant → Scripts → Tourne.",
      'Ajoute un champ en haut de la classe : vitesse = 90; — il apparaît dans l\'inspecteur, modifiable sans toucher au code.',
      'Lance ▶ : le cube tourne. Les erreurs s\'affichent dans la Console ; touche-les pour aller à la ligne.',
    ],
  },
  {
    title: 'Physique et collisions',
    icon: '🪨',
    steps: [
      'Ajoute un Rigidbody à un objet : il tombe avec la gravité.',
      'Les objets ont besoin d\'un Collider (Box, Sphere…) pour se toucher. Le sol n\'a pas besoin de Rigidbody.',
      'Coche « Déclencheur » sur un collider pour qu\'il soit traversable : OnTriggerEnter(other) sera appelé.',
      'Pour sauter : this.GetComponent("Rigidbody").AddForce(new Vector3(0, 6, 0), ForceMode.Impulse);',
      'En 2D, bloque la position Z et les rotations X/Y dans le Rigidbody.',
    ],
  },
  {
    title: 'Prefabs et Instantiate',
    icon: '🧩',
    steps: [
      'Crée un objet (ex. une balle), puis dans la Hiérarchie : ⋯ → « Créer un prefab ».',
      'Dans ton script : balle = Ref.Prefab("Balle");',
      'Pour en créer un : Instantiate(this.balle, this.transform.position, Quaternion.identity);',
      'Détruis-le après 2 s : Destroy(objet, 2);',
    ],
  },
  {
    title: 'Interface (score, boutons)',
    icon: '🔤',
    steps: [
      '+ → Interface → Texte. Règle l\'ancre (ex. haut-gauche) et la taille dans l\'inspecteur.',
      'Dans un script : this.scoreText = GameObject.Find("Score").GetComponent("Text");',
      'Puis : this.scoreText.text = "Score : " + this.score;',
      'Un Bouton appelle la méthode indiquée dans « Méthode OnClick » sur les scripts du même objet (ou de la scène).',
    ],
  },
  {
    title: 'Installer sur l\'iPhone',
    icon: '📱',
    steps: [
      'Ouvre CréaEngine dans Safari.',
      'Touche le bouton Partager (carré avec une flèche ↑).',
      'Choisis « Sur l\'écran d\'accueil », puis « Ajouter ».',
      "L'icône apparaît sur ton bureau : l'app s'ouvre en plein écran et marche hors ligne.",
      'Tes projets sont enregistrés dans l\'app. Pense à les exporter (Hub → ⋯ → Exporter) pour les sauvegarder.',
    ],
  },
];
